### ISSUE TITLE
Add Link to GitHub

### ISSUE THREAD

**Issue by beaufortfrancois** [beaufortfrancois/download-chromium#17]
So that people know how that works, we should link to https://github.com/beaufortfrancois/download-chromium/ from https://download-chromium.appspot.com/

**Comment by beaufortfrancois** [comment]
Fixed by https://github.com/beaufortfrancois/download-chromium/commit/ebb5ce468fb86b7b61edcbadfcffe5a74c1a1091

cc @paulirish

**Comment by beaufortfrancois** [comment]
@paullewis Does https://download-chromium.appspot.com/?platform=Android&type=snapshots look good to you?

**Comment by paullewis** [comment]
A+ would download Chrome again! :shipit:
