### ISSUE TITLE
Latest Windows Chrominum Build Missing Chrome.exe

### ISSUE THREAD

**Issue by wadedesk** [beaufortfrancois/download-chromium#18]
I downloaded the latest Windows build dated 5/17 and it does not appear to have the Windows chrome.exe in the zip folder.

**Comment by beaufortfrancois** [comment]
I just downloaded Build r395560 from https://download-chromium.appspot.com/?platform=Win&type=snapshots and I can see `chrome.exe` in the chrome-win32 folder.
Please reopen if you're still seeing this issue.
