### ISSUE TITLE
LKGR no longer being updated

### ISSUE THREAD

**Issue by wfdd** [beaufortfrancois/download-chromium#19]
The LKGR channel appears to be no more - see [1](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/YL4GAwoWfZU), [2](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/FsOMxGaufOM), [3](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/lKLCCjKjvJc).  Would there be a substitute 'stable' channel to hook up to?

**Comment by paulirish** [comment]
good call. thank you!

**Comment by beaufortfrancois** [comment]
I'm not aware of a stable channel to hook up to.
What we could do though is to use https://omahaproxy.appspot.com/ to provide Dev/Beta/Stable Chromium builds based on Google Chrome. What do you think?

**Comment by wfdd** [comment]
IIRC, the last time this was brought up at brew-cask, Paul said the Chrome version numbers indicate the point at which Chrome was forked from Chromium in prep for a release, not the actual version that was released... which is kinda nonsensical, come to think about it.  I might be remembering wrong.

**Comment by paulirish** [comment]
Shall we remove lkgr/continuous from the UI?

**Comment by beaufortfrancois** [comment]
We should ;)
I've pushed https://github.com/beaufortfrancois/download-chromium/commit/a083b7206ea1bc111b7094fe0d5142b155c7cc29
Have a look at https://download-chromium.appspot.com/?platform=Mac&type=snapshots
