### ISSUE TITLE
Chromium snapshots for linux are not linked against libav

### ISSUE THREAD

**Issue by baco** [beaufortfrancois/download-chromium#21]
Chromium snapshots built for Linux64 are not linked against libav, so codecs like AAC, H.264 or MP3 can not be reproduced.

Please provide a version linked against libav.

**Comment by beaufortfrancois** [comment]
Chromium snapshots won't include proprietary codecs. Here's how you can build chromium by yourself though: https://plus.google.com/+FrancoisBeaufort/posts/NHYa95SZphm
