### ISSUE TITLE
Cannot sign in with google account …

### ISSUE THREAD

**Issue by fooness** [beaufortfrancois/download-chromium#22]
Dear chromium team,

since my update to Chromium 55, I cannot sign in to google anymore (to sync my bookmarks and whatever). I don’t get any errors or such, it just won’t sign in. (If I enter a wrong two factor authentication key, though, then an error message is shown.)

My operating system is latest OS X. The update before that was like three weeks ago, so I cannot exactly say, since when this bug may be existing.

```
Basic Information
Chrome Version	55.0.2865.0 (Developer Build 9ea2a739531edffad0859fdfd0a53f1f039026e4-refs/heads/master@{#419399} Mac OS X)	 
New Profile Management?	On	 
Account Consistency?	Off	 
Signin Status	Not Signed In	 
Last Signin Details
Gaia Authentication Result	Successful	9/18/16, 6:24:50 PM
RefreshToken Received	Failure	9/18/16, 6:24:51 PM
```

Hope you have any idea how to fix this.

**Comment by beaufortfrancois** [comment]
You may want to file this issue at crbug.com/new.
