### ISSUE TITLE
HTML5 player on Android.

### ISSUE THREAD

**Issue by vitumen** [beaufortfrancois/download-chromium#23]
Hi there.

I'm not sure if this is the appropriate channel to make this complain, but the last few versions of Chromium for Android have a very annoying bug.

They can't display any HTML5 player on any page.

Sorry for not give a very technical description, and sorry if this is a known bug, but i'm a recent Chromium user on Android.
By the way, i'm on  4.4.4 KitKat.

Thanks.

**Comment by beaufortfrancois** [comment]
Please file a bug at crbug.com/new
