### ISSUE TITLE
Last update was 8 months ago

### ISSUE THREAD

**Issue by fusion809** [beaufortfrancois/download-chromium#24]
Hi,

Per [probonopd/AppImages#142](https://github.com/probonopd/AppImages/issues/142#issuecomment-261704285) the last update to your download page for Linux 64-bit was 8 months ago. It contains Chromium 51 as its latest release.

Thanks for your time,
Brenton

**Comment by beaufortfrancois** [comment]
Using https://download-chromium.appspot.com/?platform=Linux_x64&type=snapshots seems to be the only way for now to get a recent build of Chromium for Linux x64.
Please open a bug at http://crbug.com/new to inform the Chromium Infra team about this.
