### ISSUE TITLE
Win x86 Last Good Revision Stale?

### ISSUE THREAD

**Issue by LarryLACa** [beaufortfrancois/download-chromium#27]
When I checked today 7/7/17 for Win x86 Chromium, the Last Known Good Revision was 382014, from 1 year ago.  This doesn't seem right.
Using: https://download-chromium.appspot.com/?platform=Win&type=continuous

**Comment by beaufortfrancois** [comment]
Yeah. known issue...
You might want to check latest ones at https://download-chromium.appspot.com/?platform=Win&type=snapshots
