### ISSUE TITLE
LKGR is dead

### ISSUE THREAD

**Issue by avidrissman** [beaufortfrancois/download-chromium#29]
There are two "build types" available for download: "Latest" and "Last Known Good Revision". The "Latest" build as of this moment is r512404, updated an hour ago. The "Last Known Good Revision" build as of this moment is r382014, updated a year ago.

LKGR in Chromium is essentially obsolete; see [this thread](https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/lKLCCjKjvJc/cW3yJESIAgAJ) and [that thread](https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/e4lQRKYbRJY/zNebDVTEuwcJ).

You should remove LKGR from this tool.

**Comment by kpeckett** [comment]
This appears to still be an issue... luckily I searched before posting a new issue.

**Comment by beaufortfrancois** [comment]
Thanks for bringing this up to my attention again. I'll experiment with removing LKGR support. See https://github.com/beaufortfrancois/download-chromium/pull/38

**Comment by beaufortfrancois** [comment]
https://download-chromium.appspot.com/ has been updated.
