### ISSUE TITLE
Download Chromium for Windows x86 (Latest) intermittently alternates between newest and second newest build

### ISSUE THREAD

**Issue by ChromiumLogoSpinner** [beaufortfrancois/download-chromium#30]
Download Chromium for Windows x86 (Latest, not LKGR) is constantly and intermittently alternating between the newest and second newest build of Chromium. For example, right now, it is intermittently alternating between build 527474 (newest) and 527470 (second newest), offering one or the other for download by the refresh.

**Comment by beaufortfrancois** [comment]
As https://commondatastorage.googleapis.com/chromium-browser-snapshots/Win/LAST_CHANGE returns a header of `cache-control:public, max-age=3600`, I had to use a hack to always get the latest version. See https://github.com/beaufortfrancois/download-chromium/commit/ea8be355635240dd8a0a464dd4c9b247ddf08a08

It should be fixed now.
Thank you @ChromiumLogoSpinner!

FYI @paulirish
