### ISSUE TITLE
Links to chromium.org are HTTP but should be HTTPS

### ISSUE THREAD

**Issue by ChromiumLogoSpinner** [beaufortfrancois/download-chromium#31]
Upon opening https://download-chromium.appspot.com, there are two links to Chromium.org that are HTTP when HTTPS would be more secure: firstly, the "Dev Channel" link, and secondly, the "Chromium team" link. Both of these links should be changed to HTTPS.

**Comment by beaufortfrancois** [comment]
You're right. I've just fixed this at https://github.com/beaufortfrancois/download-chromium/commit/89fef24cb97a8447f72a6ea2092b21b66c68816e and deployed an update at https://download-chromium.appspot.com/

FYI @paulirish
