### ISSUE TITLE
Chromium builds are too old

### ISSUE THREAD

**Issue by ChromiumLogoSpinner** [beaufortfrancois/download-chromium#37]
The Chromium builds seem to only be pulled in once every 30 minutes to an hour, and even then, the commits pulled are usually about 30 to 45 minutes old. Instead, it should be pulling from raw, raw (the freshest) commits every 15 minutes or so.

**Comment by paulirish** [comment]
We're not able to support that sort of response time. 
If you have a need for that, I'd suggest setting up your own builders.
