### ISSUE TITLE
Build revision link 404's

### ISSUE THREAD

**Issue by alystair** [beaufortfrancois/download-chromium#42]
Link to build revision results in a 404 from the following URL: https://download-chromium.appspot.com/

**Comment by beaufortfrancois** [comment]
Which one?

**Comment by alystair** [comment]
It was originally the link in the screenshot but it seems to be working now - might have broken on the one specific build that was there at the time I posted the report.

![image](https://user-images.githubusercontent.com/159109/40192603-dd258bc4-59d2-11e8-8513-d5f430ae9c86.png)

Feel free to close if you think it was a one-off issue.

**Comment by beaufortfrancois** [comment]
I think* it was.
I'll close for now and re-open if needed.

Thanks for the feedback by the way!
