### ISSUE TITLE
New directories for Windows

### ISSUE THREAD

**Issue by mikhaelkh** [beaufortfrancois/download-chromium#43]
The latest Chromium snapshot builds for Windows were moved to new subdirectories: "win32_rel" (formerly "Win") for 32-bit versions, and "win_rel" (formerly "Win_x64") for 64-bit versions.

So the new URLs are:

https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=win32_rel/
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=win_rel/

**Comment by mikhaelkh** [comment]
Seems like old subdirectories are again working and new ones stopped working.

**Comment by paulirish** [comment]
Dont' know if it's still this same issue but the current windows downloads are 404ing

**Comment by paulirish** [comment]
I think its because the archives have been renamed.

`chrome-win32.zip` => `chrome-win.zip`


![image](https://user-images.githubusercontent.com/39191/45644455-9eea6680-ba72-11e8-8ec9-73a6256d92eb.png)

I'm seeing some updates on the Chromium side for this, too...

**Comment by paulirish** [comment]
Me and the ChromeDriver folks (john chen) cant find where the tooling change was made, but John identified that `591478` is when the change was made.
