### ISSUE TITLE
Chromium OS does not start downloading

### ISSUE THREAD

**Issue by DmntGmr** [beaufortfrancois/download-chromium#47]
On the download page of Chromium OS for Linux (https://download-chromium.appspot.com/?platform=Linux_ChromiumOS_Full&type=snapshots) when I click the downloadchromium button the download does not start and shows an error.

**Comment by beaufortfrancois** [comment]
Thanks for raising this issue @DmntGmr!
I've fixed it at https://github.com/beaufortfrancois/download-chromium/commit/18dc02bc1616a1ae1933059a157d2ff0eb02d2af and deployed new version.

https://download-chromium.appspot.com/?platform=Linux_ChromiumOS_Full&type=snapshots should work now.

@paulirish I've migrated back to "secure-python27" version.
