### ISSUE TITLE
There's a little problem.

### ISSUE THREAD

**Issue by ghost** [beaufortfrancois/download-chromium#51]
I am a Chromium Android 76 user.

The browser always appears red frame How can I close it?
I followed this practice, but it didn't work.

https://github.com/kuoruan/Chromium-Android/issues/13

Click settings are still displayed, how to solve this problem?

@beaufortfrancois

**Comment by beaufortfrancois** [comment]
Please file a bug at crbug.com/new for Chromium problem. Thank you ;)
