### ISSUE TITLE
trouble downloading

### ISSUE THREAD

**Issue by austinvanstaal** [beaufortfrancois/download-chromium#67]
When I attempt to download the following appears, any idea what the issue is?
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: chromium-browser-snapshots/Android/913327/chrome-android.zip</Details>
</Error>t

**Comment by austinvanstaal** [comment]
@beaufortfrancois @paulirish please help me

**Comment by brendankenny** [comment]
It looks like the download paths have changed and need to be updated.
