### ISSUE TITLE
macOS arm

### ISSUE THREAD

**Issue by chromer030** [beaufortfrancois/download-chromium#70]
As there is an up-to-date arm builds for macOS , in this [directory](https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac_Arm/) , please include it in [website](https://download-chromium.appspot.com/).
thanks.

**Comment by beaufortfrancois** [comment]
Thanks for the heads up @chromer030!
I'll have a look

**Comment by beaufortfrancois** [comment]
And here we are. Both Intel and ARM exist:
- https://download-chromium.appspot.com/?platform=Mac&type=snapshots
- https://download-chromium.appspot.com/?platform=Mac_Arm&type=snapshots
