### ISSUE TITLE
Mac ARM Build damaged

### ISSUE THREAD

**Issue by timoschilling** [beaufortfrancois/download-chromium#72]
The latest download from https://download-chromium.appspot.com/?platform=Mac_Arm&type=snapshots produces the following error message on a M1 MacBook Air.
<img width="372" alt="Screenshot 2021-11-03 at 11 32 15" src="https://user-images.githubusercontent.com/165599/140045141-81922089-f006-42c7-bd53-7d92f895d690.png">

**Comment by beaufortfrancois** [comment]
I can't reproduce right now. Do you still the same issue?

**Comment by timoschilling** [comment]
Still the same issue, maybe it's a issue with BigSur. I have this issue on two BigSur M1 systems.

**Comment by beaufortfrancois** [comment]
Note that http://download-chromium.appspot.com/ simply links to builds created by the Chromium team. 
You may want to file a Chromium issue at crbug.com/new to let the team know of.

**Comment by timoschilling** [comment]
FTR: Problem still exists under Monterey.

I will close this issue and file one on crbug.com

**Comment by racom-oss** [comment]
@timoschilling 

Please try
/usr/bin/xattr -cr /Applications/Chromium.app
after unzip and putting Chromium.app in the Applications folder.

Hope this helps
