### ISSUE TITLE
Don't start on Mac M1

### ISSUE THREAD

**Issue by BornInWeb** [beaufortfrancois/download-chromium#75]
<img width="416" alt="Capture d’écran 2022-07-02 à 04 52 05" src="https://user-images.githubusercontent.com/41885458/176984076-1b667952-e5fa-4ff1-8a74-c89255c37702.png">

Build Revision: 1020327

**Comment by beaufortfrancois** [comment]
Thank you @BornInWeb!
I can reproduce the issue with Build Revision 1020539.
As this web app only links to pre-built binaries, I'll ping the appropriate folks to let them know so that they can fix it.

**Comment by beaufortfrancois** [comment]
FYI The build was downloaded from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac_Arm/1020539/

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/634478/177159544-e98394f8-b1d7-46b1-ade0-2062ee88a77d.png">

**Comment by rmst** [comment]
I just tried a whole bunch of Mac_Arm binaries from commondatastore all the way back to May but none worked. Are so few people downloading Chromium binaries that no one noticed this until now? Also why was this issue closed?

**Comment by rmst** [comment]
These are genuine questions. I'm not super familiar with Chromium but interested in how it's built and distributed so I was hoping @beaufortfrancois would be able to shed some light on why all these Mac binaries are faulty. E.g. maybe they used to work but a MacOS update broke them.

The second question "why was this issue closed?" is genuine too. The current binary still doesn't work (on my M1 Macbook Air at least) so the issue doesn't seem be resolved and others might find the information in here useful

**Comment by beaufortfrancois** [comment]
I've found the root cause. According to https://chromium.googlesource.com/chromium/src/+/main/docs/mac_arm64.md#building-for-arm-macs, 

> If you zip, upload Chromium.app to some web service and download it to an Arm Mac, browsers will set the `com.apple.quarantine bit`, which will cause the Finder to say `"Chromium is damaged and can't be opened. You should move it to the Trash."`... To fix this, open a terminal and run
```
% cd ~/Downloads && xattr -rc Chromium.app
```

I've tried it and it works great. I'm talking to chrome team to see if there's something to improve the current situation.

As a reminder, https://download-chromium.appspot.com/ is a simple tool that points to existing Chromium builds.

**Comment by rmst** [comment]
Ah perfect, thank you! Maybe it's because the App isn't signed (properly)?
