### ISSUE TITLE
Can't sign in to Google account on Chromium 106.0.5239.0 (Developer Build) (64-bit)

### ISSUE THREAD

**Issue by guest271314** [beaufortfrancois/download-chromium#78]
![Screenshot_2022-08-14_14-43-46](https://user-images.githubusercontent.com/4174848/184556251-b0dd4e98-dfe5-4f44-a531-f3eb699cd44b.png)

**Comment by guest271314** [comment]
Same on 106.0.5241.0 (Developer Build) (64-bit) Revision 16e36d09521376862619779f438e4bc65ba5b346-refs/heads/main@{#1034930}.

Can't sign in to Google account.

Why?

**Comment by harisonkhlil** [comment]
Yeah, I am the same problem.

**Comment by guest271314** [comment]
@harisonkhlil After some research the source of this could be https://groups.google.com/a/chromium.org/g/chromium-packagers/c/SG6jnsP4pWM/m/Y73W4CecCQAJ. I am not sure how or why this extends to Chromium builds, as I am able to sign in to Google/Gmail on Firefox 104, particular since https://download-chromium.appspot.com/ states

> now maintained by the [Chromium team](https://www.chromium.org/)

not a *nix Chromium package maintainer.

**Comment by harisonkhlil** [comment]
So, How to solve it?

**Comment by harisonkhlil** [comment]
Also, are you having trouble playing videos with Chromium?

**Comment by guest271314** [comment]
> So, How to solve it?

I don't know. This might be working as intended.

> Also, are you having trouble playing videos with Chromium?

No. Chromium does not support MP4 playback in `<video>` element.

**Comment by guest271314** [comment]
@harisonkhlil It looks like this option in Settings => Sync and Google Services is available on Chrome, not on Chromium
> Allow Chrome sign-in
> By turning this off, you can sign in to Google sites like Gmail without signing in to > Chrome

**Comment by guest271314** [comment]
https://groups.google.com/a/chromium.org/g/chromium-dev/c/sTUniGi24sg/m/dSTlWoY4AwAJ
> There are many reasons why Chromium is inappropriate for end users. Chromium does not get updated with security fixes (other than the latest build), it's not tested to the same extent as Chrome, Google API keys are missing, and as you've seen, some features get enabled on Chromium builds before they're ready for release. Chromium builds mostly are meant for developing and testing Chromium.

https://groups.google.com/a/chromium.org/g/chromium-dev/c/sTUniGi24sg/m/QNTaGLk4AwAJ
> ...to that end, if you've discovered a bug in Chromium, great! The bug report is appreciated. But we don't offer support for actually using Chromium as your daily browser.
