### ISSUE TITLE
Default to LKGR link?

### ISSUE THREAD

**Issue by paulirish** [beaufortfrancois/download-chromium#8]
It's monday. 
LKGR is currently a build from sunday. 
And the site offers me a build from a few hours ago.

Build I was offered from the site is in green on the left. Blue is LKGR.

![image](https://cloud.githubusercontent.com/assets/39191/11353165/9a3b2dd4-91f5-11e5-819c-d78255475f93.png)

Feels like it's better to offer the choice of LKGR or latest build possible. I know I would use both.

**Comment by beaufortfrancois** [comment]
Giving choice would be good indeed!
I personally enjoy latest build possible but I understand why LGKR might also fits some needs.

Let me think about it.

**Comment by beaufortfrancois** [comment]
It looks like it would be as "simple" as:

```diff
- LAST_REVISION_TEMPLATE = 'https://commondatastorage.googleapis.com/chromium-browser-snapshots/%(platform)s/LAST_CHANGE'
- LAST_SNAPSHOT_TEMPLATE = 'https://commondatastorage.googleapis.com/chromium-browser-snapshots/%(platform)s/%(revision)s/%(zip_name)s'
+ LAST_REVISION_TEMPLATE = 'https://commondatastorage.googleapis.com/chromium-browser-continuous/%(platform)s/LAST_CHANGE'
+ LAST_SNAPSHOT_TEMPLATE = 'https://commondatastorage.googleapis.com/chromium-browser-continuous/%(platform)s/%(revision)s/%(zip_name)s'

I'll come with a way to do that shortly then.
