### ISSUE TITLE
"Chromium is damaged" on mac M1

### ISSUE THREAD

**Issue by Alyetama** [beaufortfrancois/download-chromium#82]
**Binary:** Chromium for Mac ARM ([pre-built binary](https://download-chromium.appspot.com/?platform=Mac_Arm&type=snapshots))
**Build Revision:** 1055822
**System:** macOS 12.6 21G115 arm64

<img width="251" alt="Screen Shot 2022-10-06 at 1 31 09 PM" src="https://user-images.githubusercontent.com/56323389/194380859-c8788224-8157-47a2-9a61-572c4894449e.png">

**Comment by beaufortfrancois** [comment]
Hopefully https://github.com/beaufortfrancois/download-chromium/issues/75#issuecomment-1175840260 should help you ;)
