### ISSUE TITLE
Zip file can't extract or open

### ISSUE THREAD

**Issue by TuanDung0902** [beaufortfrancois/download-chromium#83]
![Screenshot 2022-10-08 164257](https://user-images.githubusercontent.com/107251718/194701163-d901d69e-7bd2-4637-87fd-f61dc0335632.jpg)

**Comment by beaufortfrancois** [comment]
This is a Chrome browser issue tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=1370961

**Comment by beaufortfrancois** [comment]
It is now fixed in Chrome 108.0.5355.0 (Chrome Canary at the time of writing)
