### ISSUE TITLE
1062551 build ZIP file is corrupted

### ISSUE THREAD

**Issue by IskandarAlex2** [beaufortfrancois/download-chromium#84]
The file is simply corrupted and I cannot read anything useful from it with WinRAR, I tried 7Zip: but nothing, and I tried file explorer: nothing.
![image](https://user-images.githubusercontent.com/65650645/197374956-192c396a-8a34-4c04-a7f5-4179e66985d4.png)

**Comment by IskandarAlex2** [comment]
it appears all of the revisions on the [page](https://download-chromium.appspot.com/) is corrupted

**Comment by beaufortfrancois** [comment]
See https://github.com/beaufortfrancois/download-chromium/issues/83
