### ISSUE TITLE
"Chromium" is damaged and can't be opened

### ISSUE THREAD

**Issue by Adjilino** [beaufortfrancois/download-chromium#88]
Can't open the most recent chromium on MacBook Air M1 

App build: **Build Revision: [1075629](https://crrev.com/1075629)** from https://download-chromium.appspot.com/?platform=Mac_Arm&type=snapshots 

<img width="269" alt="image" src="https://user-images.githubusercontent.com/38920989/203869168-aadc3fa1-8887-401b-a95c-2c857fefcfa2.png">

**Comment by beaufortfrancois** [comment]
Hopefully https://github.com/beaufortfrancois/download-chromium/issues/75#issuecomment-1175840260 should help you ;)

**Comment by Adjilino** [comment]
It works :)
Thanks
