### ISSUE TITLE
Android arm64 builds

### ISSUE THREAD

**Issue by chromer030** [beaufortfrancois/download-chromium#90]
As there is an up-to-date arm64 builds for Android , in this [directory](https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Android_Arm64/) , please include it in [website](https://download-chromium.appspot.com/).
thanks.

**Comment by beaufortfrancois** [comment]
Thank you @chromer030 for filing this feature request!
I've added Chromium for Android ARM64 builds to https://download-chromium.appspot.com/?platform=Android_Arm64&type=snapshots

FYI @paulirish
