### ISSUE TITLE
Chromium for Mac ARM fails to open

### ISSUE THREAD

**Issue by janakan2466** [beaufortfrancois/download-chromium#98]
## Summary
Chromium for Mac ARM fails to open on Apple Silicon M1 for the build version `118.0.5977.0`.

## Steps To Reproduce
1. Download Chromium for Mac ARM from: https://download-chromium.appspot.com/dl/Mac_Arm?type=snapshots
2. Go to the downloaded chrome-mac folder and open Chromium.app

## Platform
- Computer: Apple M1 Pro - Apple Silicon (AArch64  or ARM64 architecture)
- Operating System: macOS Ventura 13.4.1

## Screenshots
![chromium fail](https://github.com/beaufortfrancois/download-chromium/assets/72175053/0df08224-7a7b-4cb3-ac42-6cb5664befc0)

**Comment by beaufortfrancois** [comment]
See https://github.com/beaufortfrancois/download-chromium/issues/75#issuecomment-1175840260
